name: Automated Preprocessing

on:
  push:
    branches:
      - main
    paths:
      - 'Telco_Customer_Churn.csv'
      - 'preprocessing/**'
  workflow_dispatch:  # Manual trigger

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
        
    - name: Run preprocessing
      run: |
        cd preprocessing
        python automate_preprocessing.py --input ../Telco_Customer_Churn.csv --output ./
        
    - name: Upload preprocessed data
      uses: actions/upload-artifact@v3
      with:
        name: preprocessed-data
        path: |
          preprocessing/telco_churn_train.csv
          preprocessing/telco_churn_test.csv
        
    - name: Commit preprocessed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/telco_churn_train.csv preprocessing/telco_churn_test.csv || true
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Update preprocessed data [skip ci]"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}